# Generated by Django 3.2.10 on 2022-02-08 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0009_auto_20220205_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 13, 3, 30, 968911, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='shopuser',
            unique_together={('email',)},
        ),
    ]
